// src/experiments/spring/Experiment.svelte
<script lang="ts">
import Code from "../../components/Code.svelte";
import {
	compose,
	css,
	derive,
	formatNumber,
	framer,
	fromBounce,
	overshoot,
	presets,
	samples,
	settleTime,
	swift,
	toLinear,
} from "./logic";

let response = $state(0.55);
let dampingFraction = $state(0.825);
let mode = $state<"response" | "bounce">("response");
let demo = $state<"slide" | "scale">("slide");

const spec = $derived({ response, dampingFraction });
const d = $derived(derive(spec));
const settle = $derived(settleTime(spec));
const peak = $derived(overshoot(spec));
const linear = $derived(toLinear(spec));
const active = $derived(
	presets.find(
		(p) =>
			Math.abs(p.spec.response - response) < 1e-6 &&
			Math.abs(p.spec.dampingFraction - dampingFraction) < 1e-6,
	)?.slug,
);

/* Bounce-mode sliders write through to response and damping. */
const bounce = $derived(d.bounce);
function setBounce(b: number) {
	const s = fromBounce(response, b);
	dampingFraction = Math.round(s.dampingFraction * 1000) / 1000;
}

/* Curve geometry. Time runs to the settle time; y runs from 0 to a bit past the peak. */
const W = 420;
const H = 220;
const PAD = 28;
const yMax = $derived(Math.max(1.3, peak + 0.1));
const sx = (t: number) => PAD + (t / settle) * (W - PAD * 2);
const sy = (y: number) => H - PAD - (y / yMax) * (H - PAD * 2);
const path = $derived(
	samples(spec, 160, settle)
		.map(
			([t, y], i) =>
				`${i === 0 ? "M" : "L"} ${sx(t).toFixed(1)} ${sy(y).toFixed(1)}`,
		)
		.join(" "),
);

const timing = $derived(`linear(${linear.stops})`);
const duration = $derived(`${linear.duration}s`);
</script>

<div class="grid grid-cols-[minmax(0,1fr)] gap-8 lg:grid-cols-12 lg:gap-x-10">
  <div class="grid min-w-0 content-start gap-6 lg:col-span-4">
    <fieldset class="grid gap-2.5">
      <legend class="eyebrow mb-2">Presets</legend>
      <div class="flex flex-wrap gap-2">
        {#each presets as p (p.slug)}
          <button
            type="button"
            class="pill min-h-9 px-3.5 font-mono text-[12px] {active === p.slug ? 'pill-active' : ''}"
            aria-pressed={active === p.slug}
            title={p.note}
            onclick={() => {
              response = p.spec.response;
              dampingFraction = Math.round(p.spec.dampingFraction * 1000) / 1000;
            }}
          >{p.name}</button>
        {/each}
      </div>
    </fieldset>

    <div class="flex flex-wrap gap-2" role="group" aria-label="Parameterisation">
      <button type="button" class="pill min-h-8 px-3 text-[11px] {mode === 'response' ? 'pill-active' : ''}" aria-pressed={mode === "response"} onclick={() => (mode = "response")}>response · damping</button>
      <button type="button" class="pill min-h-8 px-3 text-[11px] {mode === 'bounce' ? 'pill-active' : ''}" aria-pressed={mode === "bounce"} onclick={() => (mode = "bounce")}>duration · bounce</button>
    </div>

    <label class="grid gap-2">
      <span class="eyebrow flex justify-between"><span>{mode === "response" ? "Response" : "Duration"} <span class="text-ink-muted">seconds</span></span><span class="text-ink tabular-nums">{formatNumber(response)} s</span></span>
      <input type="range" min="0.1" max="2" step="0.01" bind:value={response} class="accent-accent" />
      <span class="text-small text-ink-muted">One full swing of the undamped spring. Lower is stiffer and faster.</span>
    </label>

    {#if mode === "response"}
      <label class="grid gap-2">
        <span class="eyebrow flex justify-between"><span>Damping fraction</span><span class="text-ink tabular-nums">{formatNumber(dampingFraction, 3)}</span></span>
        <input type="range" min="0.1" max="1.5" step="0.005" bind:value={dampingFraction} class="accent-accent" />
        <span class="text-small text-ink-muted">Below 1 it overshoots. At 1 it just kisses the target. Above 1 it is slow and never bounces.</span>
      </label>
    {:else}
      <label class="grid gap-2">
        <span class="eyebrow flex justify-between"><span>Bounce</span><span class="text-ink tabular-nums">{formatNumber(bounce, 3)}</span></span>
        <input type="range" min="-0.5" max="0.9" step="0.01" value={bounce} oninput={(e) => setBounce(Number(e.currentTarget.value))} class="accent-accent" />
        <span class="text-small text-ink-muted">Apple's iOS 17 knob. 0 is no bounce, 0.3 is a lot, negative is sluggish.</span>
      </label>
    {/if}

    <dl class="card-flat m-0 grid grid-cols-2 gap-x-4 gap-y-3 p-4">
      <div><dt class="eyebrow">Settles in</dt><dd class="m-0 font-mono text-sm font-bold tabular-nums">{formatNumber(settle)} s</dd></div>
      <div><dt class="eyebrow">Overshoot</dt><dd class="m-0 font-mono text-sm font-bold tabular-nums">{peak > 1.001 ? `${formatNumber((peak - 1) * 100, 1)} %` : "none"}</dd></div>
      <div><dt class="eyebrow">Stiffness</dt><dd class="m-0 font-mono text-sm font-bold tabular-nums">{formatNumber(d.stiffness, 1)}</dd></div>
      <div><dt class="eyebrow">Damping</dt><dd class="m-0 font-mono text-sm font-bold tabular-nums">{formatNumber(d.damping, 2)}</dd></div>
    </dl>
  </div>

  <div class="grid min-w-0 gap-6 lg:col-span-8">
    <div class="grid gap-6 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
      <div class="grid content-start gap-2">
        <span class="eyebrow">Position over time</span>
        <svg viewBox="0 0 {W} {H}" class="card-flat w-full" role="img" aria-label="Spring position over {formatNumber(settle)} seconds, peaking at {formatNumber(peak)}">
          <line x1={PAD} y1={sy(1)} x2={W - PAD} y2={sy(1)} stroke="var(--line-soft)" stroke-width="2" stroke-dasharray="4 4" />
          <line x1={PAD} y1={sy(0)} x2={W - PAD} y2={sy(0)} stroke="var(--line-soft)" stroke-width="2" />
          <text x={PAD} y={sy(1) - 6} class="tick">target</text>
          <text x={W - PAD} y={sy(0) + 18} text-anchor="end" class="tick">{formatNumber(settle)} s</text>
          <text x={PAD} y={sy(0) + 18} class="tick">0</text>
          <path d={path} fill="none" stroke="var(--ink)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" />
          <circle cx={sx(settle)} cy={sy(1)} r="6" fill="var(--accent)" stroke="var(--line)" stroke-width="3" />
        </svg>
      </div>

      <div class="grid content-start gap-3">
        <div class="flex items-center justify-between gap-3">
          <span class="eyebrow">Preview</span>
          <div class="flex gap-1.5" role="group" aria-label="Demo">
            <button type="button" class="pill min-h-7 px-2.5 text-[11px] {demo === 'slide' ? 'pill-active' : ''}" aria-pressed={demo === "slide"} onclick={() => (demo = "slide")}>slide</button>
            <button type="button" class="pill min-h-7 px-2.5 text-[11px] {demo === 'scale' ? 'pill-active' : ''}" aria-pressed={demo === "scale"} onclick={() => (demo = "scale")}>scale</button>
          </div>
        </div>
        <div class="card-flat relative h-24 overflow-hidden [container-type:inline-size]">
          {#if demo === "slide"}
            <span aria-hidden="true" class="bg-accent border-line absolute top-1/2 left-3 size-9 -translate-y-1/2 rounded-xl border-3 motion-safe:animate-[springslide_var(--dur)_infinite_alternate]" style="--dur: {duration}; animation-timing-function: {timing}; animation-delay: 0s;"></span>
          {:else}
            <span aria-hidden="true" class="bg-blue border-line absolute top-1/2 left-1/2 size-9 -translate-1/2 rounded-xl border-3 motion-safe:animate-[springscale_var(--dur)_infinite_alternate]" style="--dur: {duration}; animation-timing-function: {timing};"></span>
          {/if}
        </div>
        <p class="text-small text-ink-muted m-0">
          The preview runs on the CSS below, not on JavaScript, so what you see here is what the browser will do with it. Back and forth, each way on the spring.
        </p>
      </div>
    </div>

    <div class="grid gap-4 sm:grid-cols-2">
      <Code code={swift(spec)} file="SwiftUI" />
      <Code code={css(spec)} file="CSS" />
      <Code code={compose(spec)} file="Jetpack Compose" />
      <Code code={framer(spec)} file="Framer Motion" />
    </div>

    <p class="text-small text-ink-muted m-0 max-w-[62ch]">
      All four describe the same physical spring with unit mass: stiffness is (2π / response)², damping is 2 · ζ · 2π / response. CSS has no spring, so the curve is sampled into <span class="font-mono">linear()</span> stops over the settle time, dropping points a straight line already covers. Apple's <span class="font-mono">bounce</span> is 1 − ζ, and its <span class="font-mono">duration</span> is the same number as <span class="font-mono">response</span>.
    </p>
  </div>
</div>

<style>
  .tick {
    fill: var(--ink-muted);
    font-family: var(--font-mono);
    font-size: 11px;
  }
  @keyframes springslide {
    to {
      transform: translate(calc(100cqw - 3.75rem), -50%);
    }
  }
  @keyframes springscale {
    from {
      transform: translate(-50%, -50%) scale(0.4);
    }
    to {
      transform: translate(-50%, -50%) scale(1.6);
    }
  }
</style>

// src/experiments/easing/Experiment.tsx
import { type PointerEvent, useId, useRef, useState } from "react";
import { type Bezier, isValid, presets, samples, toCss } from "./logic";

const labels = ["x1", "y1", "x2", "y2"] as const;

/* The curve lives in a 200 by 200 box; y may overshoot by half a box. */
const SIZE = 200;
const PAD = 24;
const OVER = 100;

export default function Experiment() {
	const [points, setPoints] = useState<Bezier>([0.2, 0.7, 0.2, 1]);
	const [copied, setCopied] = useState(false);
	const [dragging, setDragging] = useState<0 | 1 | null>(null);
	const svgRef = useRef<SVGSVGElement>(null);
	const id = useId();

	const css = toCss(points);
	const valid = isValid(points);
	const path = samples(points, 40)
		.map(([x, y], i) => `${i === 0 ? "M" : "L"} ${x * SIZE} ${SIZE - y * SIZE}`)
		.join(" ");
	const activePreset = presets.find((p) => toCss(p.points) === css)?.name;

	function update(index: number, value: number) {
		setPoints((prev) => {
			const next = [...prev] as [number, number, number, number];
			next[index] = value;
			return next;
		});
	}

	function toCurve(event: PointerEvent): [number, number] {
		const svg = svgRef.current;
		if (!svg) return [0, 0];
		const rect = svg.getBoundingClientRect();
		const viewW = SIZE + PAD * 2;
		const viewH = SIZE + OVER * 2;
		const x = ((event.clientX - rect.left) / rect.width) * viewW - PAD;
		const y = ((event.clientY - rect.top) / rect.height) * viewH - OVER;
		return [
			Math.min(1, Math.max(0, x / SIZE)),
			Math.min(1.5, Math.max(-0.5, (SIZE - y) / SIZE)),
		];
	}

	function startDrag(handle: 0 | 1) {
		return (event: PointerEvent) => {
			event.preventDefault();
			(event.target as Element).setPointerCapture?.(event.pointerId);
			setDragging(handle);
		};
	}

	function moveDrag(event: PointerEvent) {
		if (dragging === null) return;
		const [x, y] = toCurve(event);
		const round = (v: number) => Math.round(v * 100) / 100;
		setPoints((prev) => {
			const next = [...prev] as [number, number, number, number];
			next[dragging * 2] = round(x);
			next[dragging * 2 + 1] = round(y);
			return next;
		});
	}

	function endDrag() {
		setDragging(null);
	}

	async function copy() {
		try {
			await navigator.clipboard.writeText(css);
			setCopied(true);
			setTimeout(() => setCopied(false), 1600);
		} catch {
			setCopied(false);
		}
	}

	const handles: [number, number][] = [
		[points[0], points[1]],
		[points[2], points[3]],
	];

	return (
		<div className="grid grid-cols-[minmax(0,1fr)] gap-8 lg:grid-cols-12 lg:gap-x-10">
			<div className="grid min-w-0 content-start gap-6 lg:col-span-4">
				<fieldset className="grid gap-2.5">
					<legend className="eyebrow mb-2">Presets</legend>
					<div className="flex flex-wrap gap-2">
						{presets.map((preset) => (
							<button
								type="button"
								key={preset.name}
								onClick={() => setPoints(preset.points)}
								aria-pressed={preset.name === activePreset}
								className={`pill min-h-9 px-3.5 ${preset.name === activePreset ? "pill-active" : ""}`}
							>
								{preset.name}
							</button>
						))}
					</div>
				</fieldset>
				{labels.map((label, index) => (
					<label key={label} className="grid gap-2">
						<span className="eyebrow flex justify-between">
							<span>
								{label}
								<span className="text-ink-muted">
									{" "}
									{index % 2 === 0 ? "time" : "progress"}
								</span>
							</span>
							<span className="text-ink tabular-nums">
								{points[index].toFixed(2)}
							</span>
						</span>
						<input
							type="range"
							min={label.startsWith("x") ? 0 : -0.5}
							max={label.startsWith("x") ? 1 : 1.5}
							step={0.01}
							value={points[index]}
							onChange={(event) => update(index, Number(event.target.value))}
							className="accent-accent"
						/>
					</label>
				))}
			</div>

			<div className="grid min-w-0 gap-6 lg:col-span-8">
				<div className="grid gap-6 sm:grid-cols-[minmax(0,260px)_1fr]">
					<div className="grid gap-2">
						<span className="eyebrow">Curve, drag the handles</span>
						<svg
							ref={svgRef}
							viewBox={`${-PAD} ${-OVER} ${SIZE + PAD * 2} ${SIZE + OVER * 2}`}
							className={`card-flat w-full touch-none select-none ${dragging !== null ? "cursor-grabbing" : ""}`}
							role="img"
							aria-labelledby={`${id}-title`}
							onPointerMove={moveDrag}
							onPointerUp={endDrag}
							onPointerCancel={endDrag}
						>
							<title id={`${id}-title`}>
								Curve of {css}. Drag the two handles.
							</title>
							<rect
								x="0"
								y="0"
								width={SIZE}
								height={SIZE}
								fill="none"
								stroke="var(--line-soft)"
								strokeWidth="2"
							/>
							<line
								x1="0"
								y1={SIZE}
								x2={SIZE}
								y2="0"
								stroke="var(--line-soft)"
								strokeWidth="2"
								strokeDasharray="4 4"
							/>
							<line
								x1="0"
								y1={SIZE}
								x2={points[0] * SIZE}
								y2={SIZE - points[1] * SIZE}
								stroke="var(--ink-faint)"
								strokeWidth="2"
							/>
							<line
								x1={SIZE}
								y1="0"
								x2={points[2] * SIZE}
								y2={SIZE - points[3] * SIZE}
								stroke="var(--ink-faint)"
								strokeWidth="2"
							/>
							<path
								d={path}
								fill="none"
								stroke="var(--ink)"
								strokeWidth="3"
								strokeLinecap="round"
							/>
							{handles.map(([x, y], i) => (
								<circle
									key={i === 0 ? "start-handle" : "end-handle"}
									cx={x * SIZE}
									cy={SIZE - y * SIZE}
									r="11"
									fill="var(--accent)"
									stroke="var(--line)"
									strokeWidth="3"
									className="cursor-grab"
									onPointerDown={startDrag(i as 0 | 1)}
								/>
							))}
						</svg>
					</div>

					<div className="grid content-start gap-4">
						<span className="eyebrow">Preview</span>
						<div className="card-flat relative h-14 overflow-hidden [container-type:inline-size]">
							<span
								aria-hidden="true"
								className="bg-ink absolute top-1/2 left-2 size-7 -translate-y-1/2 rounded-full motion-safe:animate-[slide_1.6s_infinite_alternate]"
								style={{ animationTimingFunction: valid ? css : "linear" }}
							/>
							<style>{`@keyframes slide { to { transform: translate(calc(100cqw - 2.75rem), -50%); } }`}</style>
						</div>
						<p className="text-small text-ink-muted">
							The ball crosses on this curve, back and forth. Linear is the
							dashed diagonal; above it is fast early, below it is slow early.
						</p>
						{!valid && (
							<p className="bg-yellow text-accent-ink border-line rounded-xl border-3 px-3 py-2 text-sm font-medium">
								x1 and x2 must stay between 0 and 1 for CSS to accept the curve.
							</p>
						)}
					</div>
				</div>

				<div className="card-flat min-w-0 overflow-hidden">
					<div className="border-line flex items-center justify-between gap-3 border-b-3 px-4 py-2.5">
						<span className="eyebrow">CSS</span>
						<button
							type="button"
							onClick={copy}
							className="pill min-h-9 px-3.5"
						>
							{copied ? "Copied" : "Copy"}
						</button>
					</div>
					<pre
						// biome-ignore lint/a11y/noNoninteractiveTabindex: a scrollable region must be reachable by keyboard
						tabIndex={0}
						className="m-0 overflow-x-auto p-4 font-mono text-[13px] leading-relaxed"
					>
						{`transition-timing-function: ${css};`}
					</pre>
				</div>
				<p className="text-small text-ink-muted max-w-[60ch]">
					The y handles may leave the box; that is an overshoot, and it is how a
					spring-like settle is faked in plain CSS. The x handles may not,
					because time only moves forward.
				</p>
			</div>
		</div>
	);
}
