// src/tools/json-format/Tool.svelte
<script lang="ts">
import { formatJson } from "./logic";

let input = $state("");
let indent = $state(2);
const result = $derived(formatJson(input, indent));

const indents = [2, 4];
</script>

<div class="flex flex-col gap-[18px]">
  <label class="block">
    <span class="text-ink-soft mb-[7px] block text-[13px] font-medium">Input</span>
    <textarea
      bind:value={input}
      rows="5"
      spellcheck="false"
      placeholder={'{"hello":"world"}'}
      class="bg-surface border-line shadow-inset-field placeholder:text-ink-faint focus:border-accent w-full resize-y rounded-xl border px-4 py-3.5 font-mono text-[13.5px] leading-relaxed outline-none transition-colors"
    ></textarea>
  </label>

  <div class="flex items-center gap-2.5">
    <span class="text-ink-soft text-[13px] font-medium">Indent</span>
    <div class="bg-chip flex rounded-full p-[3px]">
      {#each indents as value (value)}
        <button
          type="button"
          onclick={() => (indent = value)}
          aria-pressed={indent === value}
          class="rounded-full px-4 py-1.5 text-[13px] transition-colors {indent === value
            ? 'bg-accent font-semibold text-white'
            : 'text-ink-muted hover:text-ink font-medium'}"
        >
          {value}
        </button>
      {/each}
    </div>
  </div>

  {#if input.trim() !== ""}
    {#if result.ok}
      <pre class="bg-surface border-line shadow-card overflow-x-auto rounded-xl border px-4 py-3.5 font-mono text-[13.5px] leading-relaxed">{result.value}</pre>
    {:else}
      <p class="bg-danger-ground border-danger-line text-danger-ink flex items-start gap-[11px] rounded-xl border px-4 py-3.5 text-[13.5px] leading-snug">
        <svg
          width="17"
          height="17"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          stroke-width="1.8"
          stroke-linecap="round"
          class="text-danger-icon mt-0.5 shrink-0"
          aria-hidden="true"
        >
          <circle cx="12" cy="12" r="9"></circle>
          <path d="M12 8v5"></path>
          <path d="M12 16.5v.01"></path>
        </svg>
        {result.error}
      </p>
    {/if}
  {/if}
</div>

// src/tools/uuid-gen/Tool.tsx
import { useState } from "react";
import { generateUuids } from "./logic";

export default function Tool() {
	const [count, setCount] = useState(5);
	const [ids, setIds] = useState<string[]>([]);
	const [error, setError] = useState<string | null>(null);

	function run() {
		const result = generateUuids(count);
		if (result.ok) {
			setIds(result.value);
			setError(null);
		} else {
			setIds([]);
			setError(result.error);
		}
	}

	return (
		<div className="flex flex-col gap-[18px]">
			<div className="flex flex-wrap items-end gap-3">
				<label className="block">
					<span className="text-ink-soft mb-[7px] block text-[13px] font-medium">
						How many
					</span>
					<input
						type="number"
						value={count}
						min={1}
						max={100}
						onChange={(e) => setCount(Number(e.target.value))}
						className="bg-surface border-line shadow-inset-field focus:border-accent w-28 rounded-xl border px-4 py-2.5 font-mono text-[13.5px] outline-none transition-colors"
					/>
				</label>
				<button
					type="button"
					onClick={run}
					className="bg-accent hover:bg-accent-deep rounded-xl px-5 py-2.5 text-[13.5px] font-semibold text-white transition-colors"
				>
					Generate UUIDs
				</button>
			</div>

			{error && (
				<p className="bg-danger-ground border-danger-line text-danger-ink flex items-start gap-[11px] rounded-xl border px-4 py-3.5 text-[13.5px] leading-snug">
					<svg
						width="17"
						height="17"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						strokeWidth="1.8"
						strokeLinecap="round"
						className="text-danger-icon mt-0.5 shrink-0"
						aria-hidden="true"
					>
						<circle cx="12" cy="12" r="9" />
						<path d="M12 8v5" />
						<path d="M12 16.5v.01" />
					</svg>
					{error}
				</p>
			)}

			{ids.length > 0 && (
				<pre className="bg-surface border-line shadow-card overflow-x-auto rounded-xl border px-4 py-3.5 font-mono text-[13.5px] leading-relaxed">
					{ids.join("\n")}
				</pre>
			)}
		</div>
	);
}
